#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.

# Uncomment following lines to run corresponding code.

matlab -nodisplay -r "addpath(genpath('/code')); Demo_MultistageCDLSR_Test"

# matlab -nodisplay -r "addpath(genpath('/code')); Demo_MultistageCDLSR_CleanTrain_NoisyTest"

# matlab -nodisplay -r "addpath(genpath('/code')); Demo_MultistageCDLSR_NoisyTrain_NoisyTest"
